server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # 1. Configuración de CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost"
            allowedMethods: "*"
            allowedHeaders: "*"
      
      # 2. Configuración de Discovery (Eureka)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # 3. Rutas manuales (Para acortar URLs)
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE       # <--- CAMBIA ESTO (Antes era AUTH-SERVICE)
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE    # <--- CAMBIA ESTO (Antes era PRODUCT-SERVICE)
          predicates:
            - Path=/api/productos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/